films/apps/film/urls.py
from django.urls import path, include
from . import views

app_name = 'film'
urlpatterns = [
    path('', views.index),
    path('genre/<int:genre_id>/', views.get_genre, name = 'get_genre'),
    path('film/<int:film_id>/', views.get_film, name = 'get_film'),
    path('films_by_search/', views.search, name = 'films_by_search'),
    path('liked_films/<int:film_id>', views.liked_films, name = 'liked_films'),
    path('create_film/', views.create_film, name = 'create_film'),
    path('register/', views.user_register, name = 'register'),
    path('profile/', views.user_profile, name = 'profile'),
    path('login/', views.user_login, name = 'login'),
    path('logout/', views.user_logout, name = 'logout'),
]

films/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('film.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

films/apps/film/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import User


class Genre(models.Model):
    genre = models.CharField('Genre', max_length = 200)

    def __str__(self):
        return self.genre
class Film(models.Model):
    name = models.CharField('Film name', max_length = 150)
    producer = models.CharField('Produser', max_length = 100)
    ceated_at = models.DateField('Created date', auto_now_add = True)
    rating = models.IntegerField('Rating', default = 0)
    warning_age = models.IntegerField('Warning age', default = 0)
    description = models.TextField('Description')
    img = models.ImageField('Image', upload_to = 'media', blank = True)
    view = models.IntegerField('Views', default = 0)
    genre = models.ForeignKey(Genre, on_delete = models.CASCADE)
    video = EmbedVideoField('embed video', null = True, blank =  True)
    path_video = models.FileField('path video', upload_to = 'video', null = True, blank =  True)

    def __str__(self):
        return self.name
class Actor(models.Model):
    name = models.CharField('Actor name', max_length = 200)
    another_films = models.TextField('Actor another films')
    age = models.IntegerField('Age', default = 0)
    img = models.ImageField('Image', upload_to = 'media', null = True)
    description = models.TextField('Actor description', null = True)
    film = models.ForeignKey(Film, on_delete = models.CASCADE, null = True, blank = True)

    class Meta:
        verbose_name = 'Actor'
        verbose_name_plural = 'Actors'

    def __str__(self):
        return self.name
class Review(models.Model):
    review_author = models.CharField('Review author', max_length = 100)
    review_text = models.TextField('Text')
    film = models.ForeignKey(Film, on_delete = models.CASCADE)

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

    def __str__(self):
        return self.review_text
class Answer(models.Model):
    answer_author = models.CharField('Answer author', max_length = 100)
    answer_text = models.TextField('Text')
    reviews = models.ForeignKey(Review, on_delete = models.CASCADE)

    def __str__(self):
        return self.answer_text
class FilmShots(models.Model):
    img = models.ImageField('Image', upload_to = 'media', blank = True)
    film = models.ForeignKey(Film, on_delete = models.CASCADE, null = True, blank = True)

    class Meta:
        verbose_name = 'Filmshot'
        verbose_name_plural = 'Filmshots'
class UserPhoto(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    photo = models.ImageField(upload_to = 'media', null = True, blank = True)

    class Meta:
        verbose_name = 'UserPhoto'
        verbose_name_plural = 'UserPhotos'
class LikedFilms(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    films = models.ForeignKey(Film, on_delete = models.CASCADE, null = True)


    def __str__(self):
        return f'user: {self.user.username}, film: {self.films.name}'
    class Meta:
        verbose_name = 'Likedfilm'
        verbose_name_plural = 'Likedfilms'
class UserCreatedFilms(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, null = True)
    films = models.ForeignKey(Film, on_delete = models.CASCADE, null = True)

    def __str__(self):
        return f'user: {self.user.username}, film: {self.films.name}'
    class Meta:
        verbose_name = 'Usercreatedfilm'
        verbose_name_plural = 'Usercreatedfilms'

class UserDescription(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    description = models.TextField('description')

    def __str__(self):
        return f'user: {self.user}, description: {self.description}' 
    
    class Meta:
        verbose_name = 'Userdescription'
        verbose_name_plural = 'Userdescriptions'

films/apps/film/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import *


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label = 0, widget = forms.TextInput(
        attrs = {'class': 'form-control-inputs', 'placeholder': 'Username'}) )

    password1 = forms.CharField(label = 0, widget = forms.PasswordInput(
        attrs = {'class': 'form-control-inputs', 'placeholder': 'Password (at least 8 characters)'}) )

    password2 = forms.CharField(label = 0, widget = forms.PasswordInput(
        attrs = {'class': 'form-control-inputs', 'placeholder': 'Password repeat'}) )

    email = forms.EmailField(label = 0, widget = forms.EmailInput(
        attrs = {'class': 'form-control-inputs', 'name': 'email', 'placeholder': 'Email'}))
    
    



    class Meta():
        model = User
        fields = ('username','email', 'password1', 'password2')

        def __str__(self):
            return User.username

films/apps/film/views.py
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import *
from .models import *


def index(request):
    G = Genre.objects.all()
    F = Film.objects.all()

    context = {
        'Genre': G,
        'Film': F
    }
    return render(request, 'base.html', context)


def get_genre(request, genre_id):
    g = Genre.objects.all()
    F = Film.objects.filter(genre_id = genre_id).all()

    context = {
        'Genre': g,
        'Film': F
    }

    return render(request, 'genre.html', context)


def get_film(request, film_id):
    f = Film.objects.get(id = film_id)
    g = Genre.objects.all()
    A = Answer.objects.all()

    f_view=f.view
    Film.objects.filter( id = film_id ).update( view = f_view + 1 )

    if Actor.objects.filter(film_id = film_id):
        a = Actor.objects.filter(film_id = film_id).all()
    else:
        a = None

    if request.method == 'POST':

        if Review.objects.filter(review_author = str(request.user.username),
                                 review_text = request.POST.get("review-text"),
                                 film_id = film_id):
            pass
        else:
            if request.POST.get("review-id", None):
                if Answer.objects.filter(answer_author = str(request.user.username),
                                         answer_text = request.POST.get("review-text"),
                                         reviews_id = request.POST.get("review-id")):
                    pass
                else:
                    Answer.objects.create(answer_author = str(request.user.username),
                                          answer_text = request.POST.get("review-text"),
                                          reviews_id = request.POST.get("review-id")).save()
            else:
                Review.objects.create(review_author = str(request.user.username),
                                      review_text = request.POST.get("review-text"),
                                      film_id = film_id).save()

    context = {
        'Film': f,
        'Genre': g,
        'Actor': a,
        'Answer': A,

    }

    return render(request, 'film.html', context)


def user_register(request):
    g = Genre.objects.all()

    if request.method == 'POST':

        reg_user = UserRegisterForm(request.POST)
        if reg_user.is_valid():

            reg_user.save()

            username = request.POST.get('username')
            password = request.POST.get('password1')
            log_user = authenticate(username = username, password = password)
            login(request, log_user)

            if UserDescription.objects.filter(user_id = log_user.id, description = request.POST.get('description')):
                pass
            else:
                UserDescription.objects.create(user_id = log_user.id,
                                               description = request.POST.get('description')).save()

            return redirect('/')

    else:
        reg_user = UserRegisterForm()

    context = {
        'user': reg_user,
        'Genre': g
    }
    return render(request, 'register.html', context)


def liked_films(request, film_id):
    if not LikedFilms.objects.filter(user = request.user, films_id = film_id):
        LikedFilms.objects.create(user = request.user, films_id = film_id).save()




    return redirect(f'/film/{film_id}')


def user_profile(request):
    if UserPhoto.objects.filter(user = request.user):
        userphoto = UserPhoto.objects.get(user = request.user)
    else:
        userphoto = ''

    if UserDescription.objects.filter(user = request.user):
        userdesc = UserDescription.objects.get(user = request.user)
    else:
        userdesc = ''

    if request.method == 'POST':

        if request.POST.get('desc-text'):
            if UserDescription.objects.filter(user = request.user) is not True:
                UserDescription.objects.create(user = request.user, description = request.POST.get('desc-text')).save()
                return redirect('/profile')

        if request.FILES.get('profile-image'):
            if UserPhoto.objects.filter(user = request.user) is not True:
                UserPhoto.objects.create(user = request.user, photo = request.FILES.get('profile-image')).save()
                return redirect('/profile')

    context = {
        'user': request.user,
        'userphoto': userphoto,
        'desc': userdesc
    }

    return render(request, 'profile.html', context)


def user_login(request):
    g = Genre.objects.all()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        login_user = authenticate(username = username, password = password)

        if login_user is not None:
            login(request, login_user)

            return redirect('/')

    context = {
        'Genre': g
    }
    return render(request, 'login.html', context)


def user_logout(request):
    logout(request)
    return redirect('/')


def search(request):
    search = request.POST.get('search')
    g = Genre.objects.all()
    f = Film.objects.filter(name__icontains = search).all()

    context = {
        'Genre': g,
        'Film': f
    }
    return render(request, 'search.html', context)

def create_film(request):

    G = Genre.objects.get(genre=request.POST.get('genre'))
    Film.objects.create(
        name=request.POST.get('name'),
        producer=request.POST.get('produser'),
        rating=request.POST.get('rating'),
        warning_age=request.POST.get('warning_age'),
        description=request.POST.get('desc'),
        img=request.FILES.get('img'),
        genre=G, path_video=request.FILES.get('path_video')
    ).save()
    F = Film.objects.get(name=request.POST.get('name'))
    UserCreatedFilms.objects.create( user = request.user, films_id = F.id).save()

    return redirect('/profile')

films/apps/film/templates/actor.html
{% extends 'base.html' %}

{% block head %}

<head>
    {% load static %}
    {% load embed_video_tags %}
    <title>FIIMS</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'base.css/' %}" />
    <link rel="stylesheet" href="{% static 'genre.css/' %}">
    <link rel="stylesheet" href="{% static 'film.css/' %}">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/12ab011246.js" crossorigin="anonymous"></script>

</head>
    
{% endblock %}

<!-- GENRES -->
{% block genres %}

<div class="categories">
    <h1>Genre</h1>
    <span><a href="/">All</a></span><br>
    {% for G in Genre %}
    <span class="categorie"><a href="{% url 'film:get_genre' G.id %}">{{G.genre}}</a></span><br>
    {% endfor %}
</div>

{% endblock %}

<!-- CONTEXT -->
{% block content %}
    <div class="actor-main-box" style='height: 70vh;'>
        <img src="{{Actor.img.url}}" style="margin-right: 10px;" alt="" align="left" height="100%" width="40%">
        <p style="letter-spacing: 1px;font-size: 14px;">
            {{Actor.name}}<br><br>
            age {{Actor.age}}<br><br>
            another actor films {{Actor.another_films}} <br><br>
            {{Actor.description}}</p><br>
    </div>
{% endblock %}

films/apps/film/templates/base.html
<!DOCTYPE html>
<html>

{% block head %}
<head>

    {% load static %}
    
    <title>FIIMS</title>
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">-->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'base.css/' %}" />

    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>-->
    <script src="https://kit.fontawesome.com/12ab011246.js" crossorigin="anonymous"></script>

</head>
{% endblock %}

<body>
    <header>
        <video src="{% static 'trailer.mp4' %}" autoplay muted loop style="position: absolute;left:0px;top:0px;height: 100%;width: 100%;transform:scaleX(1.2)"></video>
        <div class="top-main-box">
            <!--style="position: absolute;left:0px;top:0px;height: 100%;width: 100%;"-->
            
            <div class="logo-name">
                <h2 class="animate__animated animate__flip">DjangoMovie</h2>
            </div>

            <form class="search-form" method="POST" action="{% url 'film:films_by_search' %}">
                {% csrf_token %}
                    <input type="search" name="search" class="search">

                    <button type="submit" class="search-button">
                        <i class="fas fa-search"></i>
                    </button>

            </form>

            <div class="register-login-box">
                {% if user.is_authenticated %}
                    Welcome <span style="color:aqua;font-size:20px;margin:0px 5px"> {{ user.username }} </span>
                    <span class="hov"><a href="{% url 'film:profile' %}">Profile</a></span>
                    <span class="hov"><a href="{% url 'film:logout'  %}">logout</a></span>
                {% else %}
                    <span class="hov"><a href="{% url 'film:register' %}">register</a></span>
                    <span class="hov"><a href="{% url 'film:login' %}"> login</a></span>
                {% endif %}


            </div>
        </div>
    </header>

    <div class="films-in-categories" >
        {% block genres %}
        <div class="categories">
            <h1>Genre</h1>
            <span><a href="/">All</a></span><br>
            {% for g in Genre %}
            <span class="categorie"><a href="{% url 'film:get_genre' g.id %}">{{g.genre}}</a></span><br>
            {% endfor %}
        </div>
        {% endblock %}

        
        <div class="films-by-categories ">
            
            
            {% block content %}
            {% for F in Film %}
            <a href="{% url 'film:get_film' F.id %}" style="width:250px;height:450px">
            <div class="film wow pulse">

                    {% if F.img %}
                        <img width="100%" height="70%" src="{{F.img.url}}" alt="sorry" >
                    {% endif %}
                    <div class="mini-about-film-box">
                        <h2>{{F.name}}</h2>
                        <span> rating {{F.rating}}, </span> <span> views {{F.view}}</span>
                    </div>

            </div>
            </a>
            {% endfor %}
            {% endblock %}

            
            
        </div>

    </div>
    <script>
        new WOW().init()
        $('.hov').hover(function() {
            $(this).addClass('animate__animated animate__shakeX')
            setTimeout(function(){
                $('.hov').removeClass('animate__animated animate__shakeX')
            }, 1000);
        })
        
        </script>
</body>
</html>

films/apps/film/templates/film.html
{% extends 'base.html' %}

{% block head %}

<head>
    {% load static %}
    {% load embed_video_tags %}
    <title>FIIMS</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'base.css/' %}" />
    <link rel="stylesheet" href="{% static 'genre.css/' %}">
    <link rel="stylesheet" href="{% static 'film.css/' %}">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/12ab011246.js" crossorigin="anonymous"></script>

</head>
    
{% endblock %}

{% block genres %}

<div class="categories">
    <h1>Genre</h1>
    <span><a href="/">All</a></span><br>
    {% for G in Genre %}
    <span class="categorie"><a href="{% url 'film:get_genre' G.id %}">{{G.genre}}</a></span><br>
    {% endfor %}
</div>

{% endblock %}


{% block content %}
<div style="margin-bottom: 10px;width: 100%;height: 70vh;">
<img height="100%" width="40%" align='left' src="{{Film.img.url}}" style="margin-right: 2%;" alt="sorry">
    


    
<h2>{{Film.name}}</h2><br>
<span>{{Film.producer}}</span><br><br>
<span>rating {{Film.rating}} </span><br><br>
<big>{{Film.warning_age}}+</big><br><br>
<span>{{Film.view}} views</span><br><br>

<!-- Actors -->
{% if Film.actor_set.count is not 0 %}
    {% for a in Film.actor_set.all %}
        <span class="actor-preview" data-img="{{a.img.url}}">
            {{a.name}}
        </span>

    {% endfor %}
    <br><br>
{% endif %}

<span>
        {% if user.is_authenticated %}
        <a href="{% url 'film:liked_films' Film.id %}"><i style="font-size:20px;margin-right:10px" class="far fa-thumbs-up"></i></a>
        or
        <a href=""><i style="font-size:20px;margin-left:10px" class="far fa-thumbs-down"></i></a>
        {% endif %}
</span>


</div>

<p style="font-weight: normal;line-height: 20px">Film created at {{Film.ceated_at|date:'Y.m.d'}} <br><br>{{Film.description}}</p>


{% if Film.video %}
    <div style="width:100%">
        {% video Film.video '850x400' %}
    </div>
{% elif Film.path_video %}
    <div style="width:100%">
        <video src="{{ Film.path_video.url }}" controls width="100%" ></video>
    </div>
{% endif %}

{% if Film.filmshots_set.count is not 0 %}
<h3>Film shots</h3>
<div style="width:100%;height:300px;display:flex">

    {% for I in Film.filmshots_set.all %}
        <img src="{{I.img.url}}" alt="image does not loading" width="33%" height="100%" style="margin-right:0.3%">
    {% endfor %}

</div>
{% endif %}


    <br><br><br><br>
    <div class="reviews-main-box">
        {% if Film.review_set.count is not 0 %}
        <big>Reviews ( {{Film.review_set.count}} )</big>
        {% endif %}
        {% for F in Film.review_set.all %}

            <div class="review-and-answers-box">
                <div class="review-box">

                    <h1>{{F.review_author}}</h1>
                    <span>{{F.review_text}}</span><br><br>
                    <a href="#reviewform"><button class="answer" onclick="answer( `{{F.review_text}}`, `{{F.id}}`)">To answer</button></a>

                </div>
                <br><br>

                {% if F.answer_set.count is not 0 %}
                <big style="margin-left:5%">Answers ( {{F.answer_set.count}} )</big>
                {% endif %}

                {% for A in F.answer_set.all %}

                <div class="answer-box">
                    <h2>{{A.answer_author}}</h2>
                    <span>{{A.answer_text}}</span><br><br>


                </div>
                {% endfor %}
            </div>

        {% endfor %}
{% if user.is_authenticated %}
        <form class="review-form" action="" method="POST" id="reviewform">

            {% csrf_token %}
            <h1>Reviews</h1>
            <textarea type="text" name="review-text" cols="40" rows="7"></textarea><br>
            <input type="hidden" name="review-id" id="review-id">
            <button type="submit" id="btn-submit">Give feedback</button>

        </form>
    </div>

    <script>
        function answer(name, id){
            $('textarea').val(name)
            $('#review-id').val(id)
            $('#btn-submit').html('To answer')
        }

    </script>


{% endif %}

{% endblock %}

films/apps/film/templates/genre.html
{% extends 'base.html' %}

{% block head %}
<head>
    {% load static %}
    <title>FIIMS</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'base.css/' %}" />
    <link rel="stylesheet" href="{% static 'genre.css/' %}">
    <script src="https://kit.fontawesome.com/12ab011246.js" crossorigin="anonymous"></script>
</head>
    
{% endblock %}

{% block genres %}

<div class="categories">
    <h1>Genre</h1>
    <span><a href="/">All</a></span><br>
    {% for G in Genre %}
    <span class="categorie"><a href="{% url 'film:get_genre' G.id %}">{{G.genre}}</a></span><br>
    {% endfor %}
</div>
{% endblock %}


{% block content %}

{% for f in Film %}
<a href='{% url "film:get_film" f.id %}' style="width: 250px">
<div class="film">

    <img height="80%" width="100%" src="{{f.img.url}}" alt="image">
    
    <h2>{{f.name}}</h2>
    <div class="mini-about-film-box">
        <span>rating {{f.rating}}, </span>
        <span>{{f.view}} views</span>
    </div>

</div>
</a>
{% endfor %}

{% endblock %}

films/apps/film/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load embed_video_tags %}
    <meta charset="UTF-8">
    <title>PROFILE</title>
    <link rel="stylesheet" href="{% static 'profile.css' %}">

    
</head>

<body>


<div class="profile-info">

    <div style="display: flex;">

        {% if userphoto.photo %}
        <div class="img-box">
            <img style="border-radius: 50%;margin-top:10%;box-shadow: 5px 5px 10px rgb(47, 122, 110);" src="{{ userphoto.photo.url }}" alt="" width="50%" height="50%">
        </div>
        {% else %}

        <div class="img-box" style="margin:auto">
            <br>

            <form action="" method="post" enctype="multipart/form-data" style="margin-top:10px;">
                {% csrf_token %}

                
                <label for="file" class="file">upload image</label><br><br>

                <input type="file" id="file" name="profile-image" style="display: none;"><br>
                <button>Upload</button>
            </form>

        </div>

        {% endif %}
        
        <div class="info-box">
    
            <h1>{{user.username}}</h1>
            <h4>email: {{user.email}}</h4>

            {% if desc.description %}
            <p>description: <br><br>{{desc.description}}</p>
            {% else %}
            <span id="write-desc" style="cursor:pointer"><big>+<b> add description</b></big></span>

            <form class="desc-form" method="post">
                {% csrf_token %}
                <textarea class="desc-textarea" name="desc-text"></textarea><br>
                <button class="desc-button">Add</button>
            </form>

            {% endif %}

        </div>
    </div>
    <br>
    <div class="content">
        <h2>Created films ({{ user.usercreatedfilms_set.count }})</h2>
        <div class="user-created-films">
            {% for ufilms in user.usercreatedfilms_set.all %}

                {% if ufilms.films.video %}
                    {% video ufilms.films.video '300x200' %}

                {% elif ufilms.films.path_video %}
                    <video src="{{ ufilms.films.path_video.url }}" controls width="300px" height="200px"></video>
                {% endif %}

            {% endfor %}

        </div>
        <br><br>
        <h2>Liked films ({{ user.likedfilms_set.count }})</h2>

        <div class="user-liked-films">
            {% for like in user.likedfilms_set.all %}
                {% video like.films.video '370x200' %}
            {% endfor %}
        </div>
    </div>

</div>

<h1 style="text-align:center">Create film and be creature!</h1>
<form action="{% url 'film:create_film' %}" method="post" class="film-create-form" enctype="multipart/form-data">
    {% csrf_token %}


    <div style="width:33%;text-align:center">
        <input type="text" class="film-create-form-inputs" placeholder="name" name="name"><br><br><br><br>
        <input type="text" class="film-create-form-inputs" placeholder="produser name" name="produser"><br><br><br><br>
        <input type="number" class="film-create-form-inputs" placeholder="rating" name="rating">
    </div>

    <div style="width:33%;text-align:center">
        <input type="number" class="film-create-form-inputs" placeholder="warning age" name="warning_age"><br><br><br><br>
        <input type="text" class="film-create-form-inputs" placeholder="genre" name="genre"><br><br><br>
        <textarea class="film-create-form-inputs" rows="5" placeholder="description" name="desc"></textarea><br><br><br>

    </div>

    <div style="width:33%;text-align:center">
        <p><big>Select film preview</big></p>
        <input type="file" id="film-img-file" name="img" style="display:none">
        <label for="film-img-file" class="file">upload preview</label><br><br>

        <p><big>Select film video</big></p>
        <input type="file" id="film-img-video" name="path_video" style="display:none">
        <label for="film-img-video" class="file-video">upload video</label>

    </div>

    <button style="position: a;position: absolute;left: calc(50% - 75px);bottom: 3%;">CREATE!</button>

</form>

<script>
    if (document.querySelector('#file') != null){
    document.querySelector('#file').addEventListener('change', function(e){
        document.querySelector('.file').innerText=`Selected image is ${e.target.files[0].name}`
        document.querySelector('.file').style.padding='10px'
        document.querySelector('.file').style.color='violet'
    })}

    if (document.querySelector('#film-img-file') != null){
    document.querySelector('#film-img-file').addEventListener('change', function(e){
        document.querySelector('.file').innerText=`Selected image is ${e.target.files[0].name}`
        document.querySelector('.file').style.padding='10px'
        document.querySelector('.file').style.color='violet'
    })}

    if (document.querySelector('#film-img-video') != null){
    document.querySelector('#film-img-video').addEventListener('change', function(e){
        document.querySelector('.file-video').innerText=`Selected video is ${e.target.files[0].name}`
        document.querySelector('.file-video').style.padding='10px'
        document.querySelector('.file-video').style.color='violet'
    })}

    document.querySelector('#write-desc').onclick=function(){
        let descForm = document.querySelector('.desc-form')

        this.style.display='none'
        descForm.style.display='block'
    }

</script>

</body>
</html>

films/apps/film/templates/search.html
{% extends 'base.html' %}
{% block head %}
<head>
    {% load static %}
    <title>FIIMS</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'base.css/' %}" />

    <script src="https://kit.fontawesome.com/12ab011246.js" crossorigin="anonymous"></script>
</head>
    
{% endblock %}

{% block genres %}

<div class="categories">
    <h1>Genre</h1>
    <span><a href="/">All</a></span><br>
    {% for G in Genre %}
    <span class="categorie"><a href="{% url 'film:get_genre' G.id %}">{{G.genre}}</a></span><br>
    {% endfor %}
</div>
{% endblock %}


{% block content %}

{% for f in Film %}
<a href='{% url "film:get_film" f.id %}' style="width: 250px">
<div class="film">

    <img height="80%" width="100%" src="{{f.img.url}}" alt="image">
    
    <h2>{{f.name}}</h2>
    <div class="mini-about-film-box" style="border:none">
        <span>rating {{f.rating}}, </span>
        <span>{{f.view}} views</span>
    </div>

</div>
</a>
{% endfor %}

{% endblock %}